name: mlops-starter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - numpy=1.24.3
  - pip
  - pip:
    - mlflow==2.8.1
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - pydantic==2.5.0
    - boto3==1.34.0
    - psycopg2-binary==2.9.7
