version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflowdb
      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://mlflow-artifacts
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - minio
    command: >
      sh -c "
        pip install pymysql psycopg2-binary &&
        mlflow server 
        --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflowdb
        --default-artifact-root s3://mlflow-artifacts
        --host 0.0.0.0
        --port 5000
      "

  model-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: random_forest_regressor
      MODEL_VERSION: latest
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    command: python src/inference.py

volumes:
  postgres_data:
  minio_data:
