apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlops
type: Opaque
stringData:
  backend-store-uri: "postgresql://mlflow:password@your-rds-endpoint:5432/mlflowdb"
  artifact-root: "s3://your-mlflow-artifacts-bucket"
  aws-access-key-id: "your-aws-access-key"
  aws-secret-access-key: "your-aws-secret-key"
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops
